### ISSUE TITLE
Initial Submission Resubmission - Courtney

### ISSUE THREAD

**Issue by brandondombrowsky** [brandondombrowsky/NeverLetGo#23]
As a developer, I will become stronger in my skills as I learn more about my discipline. AFTER completing the extended Titanic tutorial, I will rework my original submission in the hopes of achieving a higher score. 

Story Points: 6-8

**Comment by CourtneyHoppus** [comment]
<img width="1278" alt="image" src="https://github.com/brandondombrowsky/NeverLetGo/assets/74206103/3725848a-835f-44b8-9bc1-61d3c712e569">
