### ISSUE TITLE
Titanic Tutorial - Kristin

### ISSUE THREAD

**Issue by brandondombrowsky** [brandondombrowsky/NeverLetGo#3]
As a data scientist on a new project, I will need to first join the "Titanic - Machine Learning from Disaster" competition by clicking on the underlined "Join Competition button" link in the third paragraph at (https://www.kaggle.com/competitions/titanic).

I will then complete the initial tutorial to gain permission to form a group. Group formation will begin ONLY after I submit my first prediction --> by following the Titanic Tutorial steps until the end (https://www.kaggle.com/code/alexisbcook/titanic-tutorial/notebook).

Story Points: 4

**Comment by KristinJJ** [comment]
![Image](https://github.com/brandondombrowsky/NeverLetGo/assets/26866132/b11ee7fd-7d00-4221-a667-894b344ecd60)
