### ISSUE TITLE
Submit a final (likely 3rd+) Kaggle prediction - Courtney

### ISSUE THREAD

**Issue by brandondombrowsky** [brandondombrowsky/NeverLetGo#39]
As a data scientist, refining my approach and improving my results is critical. Therefore, I will do one last Kaggle prediction submission in an attempt to improve my score. 

Story Points: 3-5

**Comment by CourtneyHoppus** [comment]
[Kaggle notebook for re-submission - version 2](https://www.kaggle.com/code/courtneyhoppus/courtneyresubmission/notebook?scriptVersionId=132433454)

<img width="1470" alt="Screenshot 2023-06-05 at 2 21 11 PM" src="https://github.com/brandondombrowsky/NeverLetGo/assets/74206103/b4e7199f-7fcb-4b7b-9aff-5557b3f8e978">
