### ISSUE TITLE
Titanic Tutorial - Courtney

### ISSUE THREAD

**Issue by brandondombrowsky** [brandondombrowsky/NeverLetGo#6]
As a data scientist on a new project, I will need to first join the "Titanic - Machine Learning from Disaster" competition by clicking on the underlined "Join Competition button" link in the third paragraph at (https://www.kaggle.com/competitions/titanic).

I will then complete the initial tutorial to gain permission to form a group. Group formation will begin ONLY after I submit my first prediction --> by following the Titanic Tutorial steps until the end (https://www.kaggle.com/code/alexisbcook/titanic-tutorial/notebook).

Story Points: 4

**Comment by CourtneyHoppus** [comment]
<img width="1470" alt="image" src="https://github.com/brandondombrowsky/NeverLetGo/assets/74206103/4a264310-feab-48d5-aba5-0a8392660481">
